# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player', models.IntegerField()),
                ('roles', models.CharField(max_length=500)),
                ('playerDetails', models.TextField()),
            ],
        ),
    ]
